/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include <math.h> 

#include "func.hpp" 
#include "Riostream.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include "TMath.h" 

ClassImp(RooMyPdf) 

RooMyPdf::RooMyPdf(const char *name, const char *title, 
                   RooAbsReal& _x,
                   RooAbsReal& _alpha) :
RooAbsPdf(name,title), 
    x("x","x",this,_x),
    alpha("alpha","alpha",this,_alpha)
{ 
} 

RooMyPdf::RooMyPdf(const RooMyPdf& other, const char* name) :  
    RooAbsPdf(other,name), 
    x("x",this,other.x),
    alpha("alpha",this,other.alpha)
{ 
} 

Double_t RooMyPdf::evaluate() const 
{ 
    // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
     return(alpha*x) ; 
}
